require:
  - 'rubocop-gitlab-security'
  - 'rubocop-performance'
  - 'rubocop-rails'

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
      - 'db/**/*'
      - 'config/**/*'
      - 'script/**/*'
      - 'bin/*'
      - 'lib/tasks/**/*'
      - 'vendor/**/*'

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/AccessModifierDeclarations:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'app/controllers/**/*'

Style/LambdaCall:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/TrivialAccessors:
  ExactNameMatch: true
  AllowPredicates: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/HashAlignment:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false # Add our behaviour

Layout/LineLength:
  Max: 99
  IgnoredPatterns: ['\A#']
  Exclude:
    - 'db/migrate/*'
    - 'spec/database/*'

Layout/ArgumentAlignment:
  Enabled: false # Align the arguments of a method call if they span more than one line

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/migrate/*'

Metrics/ClassLength:
  Max: 120

Bundler/OrderedGems:
  Enabled: false

Rails/HttpStatus:
  Enabled: false

Rails/Delegate:
  Enabled: false
